#!/usr/bin/python

def sddm(config, color_config, theme, user, screen_width=1920, screen_height=1080):
    sddm_theme = [
        """# For more info: https://github.com/JaKooLit/simple-sddm-2""",
        """[General]""",
        f"""Background="Backgrounds/{theme}.png" """,
        """DimBackgroundImage="0.0" """,
        """ScaleImageCropped="true" """,
        f"""ScreenWidth="{screen_width}" """,
        f"""ScreenHeight="{screen_height}" """,
        """FullBlur="false" """,
        """PartialBlur="true" """,
        """BlurRadius="0" """,
        """HaveFormBackground="false" """,
        """FormPosition="left" """,
        """BackgroundImageHAlignment="center" """,
        """BackgroundImageVAlignment="center" """,
        f"""MainColor="{color_config["main-fg"]}" """,
        f"""AccentColor="{color_config["main-fg"]}" """,
        """OverrideTextFieldColor="" """,
        """BackgroundColor="#030404" """,
        """placeholderColor="#bbbbbb" """,
        """IconColor="#ffffff" """,
        """OverrideLoginButtonTextColor="" """,
        """InterfaceShadowSize="6" """,
        """InterfaceShadowOpacity="0.6" """,
        """RoundCorners="20" """,
        """ScreenPadding="0" """,
        """Font="JetBrainsMono Nerd Font" """,
        """FontSize="" """,
        """HideLoginButton="false" """,
        """ForceRightToLeft="false" """,
        """ForceLastUser="true" """,
        """ForcePasswordFocus="true" """,
        """ForceHideCompletePassword="true" """,
        """ForceHideVirtualKeyboardButton="false" """,
        """ForceHideSystemButtons="false" """,
        """AllowEmptyPassword="false" """,
        """AllowBadUsernames="false" """,
        """Locale="" """,
        """HourFormat="HH:mm" """,
        """DateFormat="dddd  MMM d" """,
        """HeaderText="HELLO THERE!" """,
        """TranslatePlaceholderUsername="" """,
        """TranslatePlaceholderPassword="" """,
        """TranslateLogin="" """,
        """TranslateLoginFailedWarning="" """,
        """TranslateCapslockWarning="" """,
        """TranslateSuspend="" """,
        """TranslateHibernate="" """,
        """TranslateReboot="" """,
        """TranslateShutdown="" """,
        """TranslateVirtualKeyboardButton="" """,
        ]
    
    default_conf = [
        """[Autologin]""",
        """Relogin=false""",
        """Session=""",
        """User=""",
        """[General]""",
        """DisplayServer=x11""",
        """GreeterEnvironment=""",
        """HaltCommand=/usr/bin/systemctl poweroff""",
        """InputMethod=""",
        """Namespaces=""",
        """Numlock=none""",
        """RebootCommand=/usr/bin/systemctl reboot""",
        """[Theme]""",
        """Current=Simple-SDDM""",
        """CursorSize=24""",
        f"""CursorTheme={config["cursor-theme"]}""",
        """DisableAvatarsThreshold=7""",
        """EnableAvatars=true""",
        """FacesDir=/usr/share/sddm/faces""",
        """Font=""",
        """ThemeDir=/usr/share/sddm/themes""",
        """[Users]""",
        """DefaultPath=/usr/local/sbin:/usr/local/bin:/usr/bin""",
        """HideShells=""",
        """HideUsers=""",
        """MaximumUid=60513""",
        """MinimumUid=1000""",
        """RememberLastSession=true""",
        """RememberLastUser=true""",
        """ReuseSession=true""",
        """[Wayland]""",
        """CompositorCommand=weston --shell=kiosk""",
        """EnableHiDPI=true""",
        """SessionCommand=/usr/share/sddm/scripts/wayland-session""",
        """SessionDir=/usr/local/share/wayland-sessions,/usr/share/wayland-sessions""",
        """SessionLogFile=.local/share/sddm/wayland-session.log""",
        """[X11]""",
        """DisplayCommand=/usr/share/sddm/scripts/Xsetup""",
        """DisplayStopCommand=/usr/share/sddm/scripts/Xstop""",
        """EnableHiDPI=true""",
        """ServerArguments=-nolisten tcp""",
        """ServerPath=/usr/bin/X""",
        """SessionCommand=/usr/share/sddm/scripts/Xsession""",
        """SessionDir=/usr/local/share/xsessions,/usr/share/xsessions""",
        """SessionLogFile=.local/share/sddm/xorg-session.log""",
        """XephyrPath=/usr/bin/Xephyr"""
        ]

    with open(f"/home/{user}/.config/theme-manager/conf/sddm_theme.conf", "w", encoding="UTF-8") as file:
        file.writelines("\n".join(sddm_theme))
    
    with open(f"/home/{user}/.config/theme-manager/conf/sddm.conf", "w", encoding="UTF-8") as file:
        file.writelines("\n".join(default_conf))

