@define-color background #eff1f5;
@define-color text #4c4f69;
@define-color subtext #6c6f85;
@define-color overlay #9ca0b0;

@define-color active-background #5c5f77;
@define-color active-foreground #dce0e8;
@define-color hover-background #dc8a78;
@define-color hover-foreground #dce0e8;

@define-color pink #ea76cb;
@define-color purple #8839ef;
@define-color red #d20f39;
@define-color orange #fe640b;
@define-color yellow #df8e1d;
@define-color green #40a02b;
@define-color blue #1e66f5;