@define-color background #18100f;
@define-color text #abb1c5;
@define-color subtext #abc1bf;
@define-color overlay #778785;

@define-color active-background #FADE5C;
@define-color active-foreground #4A6B9C;
@define-color hover-background #E59F22;
@define-color hover-foreground #4A6B9C;

@define-color pink #BF73CC;
@define-color purple #6E6695;
@define-color red #965C62;
@define-color orange #E59F22;
@define-color yellow #FADE5C;
@define-color green #9BB47F;
@define-color blue #4A6B9C;